// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf0xY3T4tBLnef9OWiUfa9h4r2Z4xWX2g',
    appId: '1:751374545773:web:c5467f47461ad4a3016064',
    messagingSenderId: '751374545773',
    projectId: 'cafe-app-cf1bd',
    authDomain: 'cafe-app-cf1bd.firebaseapp.com',
    storageBucket: 'cafe-app-cf1bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9ImtyX-s-tQRPZFr55OglQR0Gs8VT8Q',
    appId: '1:751374545773:android:3da1285de9e83e36016064',
    messagingSenderId: '751374545773',
    projectId: 'cafe-app-cf1bd',
    storageBucket: 'cafe-app-cf1bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwwwEXqMT0bAYXwnF9rrmEwyGO2Gr-3ZI',
    appId: '1:751374545773:ios:a8385ecb2037cfe6016064',
    messagingSenderId: '751374545773',
    projectId: 'cafe-app-cf1bd',
    storageBucket: 'cafe-app-cf1bd.appspot.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwwwEXqMT0bAYXwnF9rrmEwyGO2Gr-3ZI',
    appId: '1:751374545773:ios:a8385ecb2037cfe6016064',
    messagingSenderId: '751374545773',
    projectId: 'cafe-app-cf1bd',
    storageBucket: 'cafe-app-cf1bd.appspot.com',
    iosBundleId: 'com.example.cafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCf0xY3T4tBLnef9OWiUfa9h4r2Z4xWX2g',
    appId: '1:751374545773:web:dc54a9c12bd706a3016064',
    messagingSenderId: '751374545773',
    projectId: 'cafe-app-cf1bd',
    authDomain: 'cafe-app-cf1bd.firebaseapp.com',
    storageBucket: 'cafe-app-cf1bd.appspot.com',
  );
}
